#
# This file is originally a copy of https://github.com/k3s-io/k3s/blob/master/docker-compose.yml
#
version: '3'
services:
  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command:
    - server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=${K3S_TOKEN:?err}
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - .:/output
    - ./registries.yaml:/etc/rancher/k3s/registries.yaml # Need to be added for each nodes
    ports:
    - 6443:6443  # Kubernetes API Server
    - 80:80      # Ingress controller port 80
    - 443:443    # Ingress controller port 443

  agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=${K3S_TOKEN:?err}
    volumes:
    - ./registries.yaml:/etc/rancher/k3s/registries.yaml # Need to be added for each nodes
    ports:
    - 8080:8080  # load balancer https://medium.com/codex/setup-local-integration-environment-with-k3s-and-docker-compose-13fd815765cc
    - 9981:9981  # load balancer service

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "abc123"
      POSTGRES_DB: "example"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # https://github.com/localstack/localstack/blob/master/docker-compose.yml
  localstack:
    image: localstack/localstack:1.0.0
    ports:
      - "0.0.0.0:4566:4566"            # LocalStack Gateway
      - "0.0.0.0:4510-4559:4510-4559"  # external services port range
    # https://docs.localstack.cloud/localstack/configuration/
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-northeast-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  registry.local:
    image: "registry:2"
    ports:
    - 5000:5000 

volumes:
  k3s-server: {}
