#
# *.env -> config-map -> vars -> $(NAME)
#
resources:
  - foo-app.yml
  - config-map.yml

configMapGenerator:
  - name: env-foo
    envs:
      - env-foo.env
  - name: common
    literals:
      - author=tmtk75

vars:
  - name: AUTHOR
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: common
    fieldref:
      fieldpath: data.author
  - name: MY_IP_ADDR
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: env-foo
    fieldref:
      fieldpath: data.my_ip_addr

replacements:
- source:
    kind: Deployment
    name: foo-app
    fieldPath: spec.template.spec.containers.[name=foo-app].image
    options:
      delimiter: ":"
      index: 2  # registry.local:5000/foo-app:latest -> registry.local  5000/foo-app  latest, 
  targets:
  - select:
      kind: Deployment
      name: foo-app
    fieldPaths:
      - spec.template.spec.containers.[name=foo-app].env.[name=VERSION].value
- source:
    kind: ConfigMap
    name: env-foo
    fieldPath: data.foo
  targets:
  - select:
      kind: Deployment
      name: foo-app
    fieldPaths:
      - spec.template.spec.containers.[name=foo-app].env.[name=FOO].value

